services:
  backend:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=3000
        - ASPNETCORE_HTTPS_PORTS=3001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fizzbuzz.pfx
    container_name: fizzbuzzbackend
    image: fizzbuzzbackend
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "3000:3000"
        - "3001:3001"
    volumes:
        - C:\Users\giand\.aspnet\https:/https:ro
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: FizzBuzzGame
    ports:
        - "5438:5432"
    volumes:
        - db-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
  frontend:
    build:
        context: ../fizzbuzzgame.client
        dockerfile: ../fizzbuzzgame.client/Dockerfile
    image: fizzbuzzfrontend
    container_name: fizzbuzzfrontend
    environment:
      NODE_ENV: development
      PORT: 5000
      HOSTNAME: "0.0.0.0"
    ports:
        - "5000:5000"
    depends_on:
        - backend
volumes:
  db-data: